/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Analysis.LexicalAnalysis;
import Analysis.Parser;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JMenuItem;






/**
 *
 * @author JoséAlberto
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private String[] line;
    public GUI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        TextLineNumber numLine = new TextLineNumber(textEditor);
        textScrollPanel.setRowHeaderView(numLine);
        textEditor.setEditable(false);
        RUN.setEnabled(false);
        Run.setEnabled(false);
        bdbutton.setEnabled(false);
        filebutton.setEnabled(false);
        savebutton.setEnabled(false);
        FixedColumnExample ejem = new FixedColumnExample();
        
        outputScrollPanel.setViewportView(ejem.table);
        //checkScrollPanel.setViewportView(ejem.fixedTable);
        
        TreeSample tre = new TreeSample();
        treeScrollPanel.setViewportView(tre.tree);
        
        checkScrollPanel.setViewportView(textCheck);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        treeScrollPanel = new javax.swing.JScrollPane();
        outputTab = new javax.swing.JTabbedPane();
        outputScrollPanel = new javax.swing.JScrollPane();
        checkScrollPanel = new javax.swing.JScrollPane();
        textCheck = new javax.swing.JTextPane();
        textScrollPanel = new javax.swing.JScrollPane();
        textEditor = new javax.swing.JTextPane();
        panelButton = new javax.swing.JPanel();
        start1 = new javax.swing.JButton();
        start = new javax.swing.JButton();
        RUN = new javax.swing.JButton();
        bdbutton = new javax.swing.JButton();
        filebutton = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Edit = new javax.swing.JMenu();
        Run = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setPreferredSize(new java.awt.Dimension(1000, 900));

        outputTab.addTab("Output", outputScrollPanel);

        checkScrollPanel.setViewportView(textCheck);

        outputTab.addTab("Check", checkScrollPanel);

        textScrollPanel.setViewportView(textEditor);

        start1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stopIcon.png"))); // NOI18N
        start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start1ActionPerformed(evt);
            }
        });

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.jpg"))); // NOI18N
        start.setPreferredSize(new java.awt.Dimension(67, 43));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        RUN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon.png"))); // NOI18N
        RUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUNActionPerformed(evt);
            }
        });

        bdbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bd.png"))); // NOI18N
        bdbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdbuttonActionPerformed(evt);
            }
        });

        filebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file.jpg"))); // NOI18N
        filebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filebuttonActionPerformed(evt);
            }
        });

        savebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(start1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RUN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bdbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(start1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(filebutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(bdbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RUN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(savebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(treeScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputTab)
                    .addComponent(panelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textScrollPanel)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputTab, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(treeScrollPanel)
        );

        File.setText("File");
        menuBar.add(File);

        Edit.setText("Edit");

        Run.setText("Run");
        Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunActionPerformed(evt);
            }
        });
        Edit.add(Run);

        menuBar.add(Edit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunActionPerformed
        // TODO add your handling code here:
          String temp="";
        setLine(textEditor.getText().split("\\n"));
        int count = 0;
       LexicalAnalysis lex = new LexicalAnalysis();
        Parser par = new Parser();
        System.out.println("Linea nueva");
        temp +="Manejo de errores\n";
        
        while (count <line.length){
           // LexicalAnalysis lex = new LexicalAnalysis();
            if (par.parse(lex.tokenize(line[count]))){
                System.out.println("True");
            }else{
                int linea = count+1;
               System.out.println("Error in line: " + linea);
                temp+="Error in line: " + linea+"\n";
         }
        count++;}
        textCheck.setText(temp);
    }//GEN-LAST:event_RunActionPerformed

    private void RUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUNActionPerformed
        // TODO add your handling code here:
                String temp="";
        setLine(textEditor.getText().split("\\n"));
        int count = 0;
       LexicalAnalysis lex = new LexicalAnalysis();
        Parser par = new Parser();
        System.out.println("Linea nueva");
        temp +="Manejo de errores\n";
        
        while (count <line.length){
           // LexicalAnalysis lex = new LexicalAnalysis();
            if (par.parse(lex.tokenize(line[count]))){
                System.out.println("True");
            }else{
                int linea = count+1;
               System.out.println("Error in line: " + linea);
                temp+="Error in line: " + linea+"\n";
         }
        count++;}
        textCheck.setText(temp);
    }//GEN-LAST:event_RUNActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        textEditor.setEditable(true);
        RUN.setEnabled(true);
        Run.setEnabled(true);
        bdbutton.setEnabled(true);
        filebutton.setEnabled(true);
        savebutton.setEnabled(true);
    }//GEN-LAST:event_startActionPerformed

    private void start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start1ActionPerformed
        // TODO add your handling code here:
        textEditor.setEditable(false);
        RUN.setEnabled(false);
        Run.setEnabled(false);
        bdbutton.setEnabled(false);
        filebutton.setEnabled(false);
        savebutton.setEnabled(false);
    }//GEN-LAST:event_start1ActionPerformed

    private void bdbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdbuttonActionPerformed

    private void filebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filebuttonActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Edit;
    private javax.swing.JMenu File;
    private javax.swing.JButton RUN;
    private javax.swing.JMenuItem Run;
    private javax.swing.JButton bdbutton;
    private javax.swing.JScrollPane checkScrollPanel;
    private javax.swing.JButton filebutton;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JScrollPane outputScrollPanel;
    private javax.swing.JTabbedPane outputTab;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelButton;
    private javax.swing.JButton savebutton;
    private javax.swing.JButton start;
    private javax.swing.JButton start1;
    private javax.swing.JTextPane textCheck;
    private javax.swing.JTextPane textEditor;
    private javax.swing.JScrollPane textScrollPanel;
    private javax.swing.JScrollPane treeScrollPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return 
     */
    public JButton getRUN() {
        return RUN;
    }

    /**
     * 
     * @param RUN 
     */
    public void setRUN(JButton RUN) {
        this.RUN = RUN;
    }

    /**
     * 
     * @return 
     */
    public JMenuItem getRun() {
        return Run;
    }

    /**
     * 
     * @param Run 
     */
    public void setRun(JMenuItem Run) {
        this.Run = Run;
    }

    /**
     * @return the line
     */
    public String[] getLine() {
        return line;
    }

    /**
     * @param line the line to set
     */
    public void setLine(String[] line) {
        this.line = line;
    }
}
